[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = {git = "https://github.com/risc0/risc0", ref = "515b80438fe82ff831d461fd3ae55a7dbce5a8b6", features = ["unstable"] } 

[package.metadata.risc0]
methods = ["guest"]
